var sourcesIndex = JSON.parse('{\
"ac_library_rs":["",[],["convolution.rs","dsu.rs","fenwicktree.rs","internal_bit.rs","internal_math.rs","internal_queue.rs","internal_scc.rs","internal_type_traits.rs","lazysegtree.rs","lib.rs","math.rs","maxflow.rs","mincostflow.rs","modint.rs","scc.rs","segtree.rs","string.rs","twosat.rs"]],\
"amplify":["",[],["as_any.rs","bipolar.rs","dumb_default.rs","flags.rs","io_error.rs","lib.rs","macros.rs","slice32.rs","strategy.rs","wrapper.rs"]],\
"amplify_derive":["",[],["as_any.rs","display.rs","error.rs","from.rs","getters.rs","lib.rs","util.rs","wrapper.rs"]],\
"amplify_num":["",[],["bigint.rs","error.rs","hex.rs","lib.rs","posit.rs","smallint.rs"]],\
"amplify_syn":["",[],["attr.rs","cls.rs","error.rs","lib.rs","parsers.rs","req.rs","val.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"either":["",[],["lib.rs"]],\
"getrandom":["",[],["error.rs","error_impls.rs","lib.rs","linux_android.rs","use_file.rs","util.rs","util_libc.rs"]],\
"itertools":["",[["adaptors",[],["coalesce.rs","map.rs","mod.rs","multi_product.rs"]]],["combinations.rs","combinations_with_replacement.rs","concat_impl.rs","cons_tuples_impl.rs","diff.rs","duplicates_impl.rs","either_or_both.rs","exactly_one_err.rs","extrema_set.rs","flatten_ok.rs","format.rs","free.rs","group_map.rs","groupbylazy.rs","grouping_map.rs","impl_macros.rs","intersperse.rs","k_smallest.rs","kmerge_impl.rs","lazy_buffer.rs","lib.rs","merge_join.rs","minmax.rs","multipeek_impl.rs","pad_tail.rs","peek_nth.rs","peeking_take_while.rs","permutations.rs","powerset.rs","process_results_impl.rs","put_back_n_impl.rs","rciter_impl.rs","repeatn.rs","size_hint.rs","sources.rs","tee.rs","tuple_impl.rs","unique_impl.rs","unziptuple.rs","with_position.rs","zip_eq_impl.rs","zip_longest.rs","ziptuple.rs"]],\
"libc":["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"num":["",[],["lib.rs"]],\
"num_bigint":["",[["bigint",[],["addition.rs","bits.rs","convert.rs","division.rs","multiplication.rs","power.rs","shift.rs","subtraction.rs"]],["biguint",[],["addition.rs","bits.rs","convert.rs","division.rs","iter.rs","monty.rs","multiplication.rs","power.rs","shift.rs","subtraction.rs"]]],["bigint.rs","biguint.rs","lib.rs","macros.rs"]],\
"num_complex":["",[],["cast.rs","complex_float.rs","lib.rs","pow.rs"]],\
"num_integer":["",[],["average.rs","lib.rs","roots.rs"]],\
"num_iter":["",[],["lib.rs"]],\
"num_rational":["",[],["lib.rs","pow.rs"]],\
"num_traits":["",[["ops",[],["checked.rs","euclid.rs","inv.rs","mod.rs","mul_add.rs","overflowing.rs","saturating.rs","wrapping.rs"]]],["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]],\
"once_cell":["",[],["imp_std.rs","lib.rs","race.rs"]],\
"ppv_lite86":["",[["x86_64",[],["mod.rs","sse2.rs"]]],["lib.rs","soft.rs","types.rs"]],\
"proc_macro2":["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"qitoy":["",[["algorithm",[],["mo.rs","mod.rs"]],["data_structure",[],["bit_vec.rs","mod.rs","wavelet_matrix.rs"]],["math",[["prime",[],["check.rs","factorise.rs","mod.rs","pi.rs","sieve.rs"]]],["combi.rs","matrix.rs","mod.rs","montgomery.rs","numeric.rs"]],["string",[],["mod.rs","rolling_hash.rs"]],["utils",[],["bound.rs","mod.rs"]],["vec",[],["merge.rs","mod.rs"]]],["lib.rs","prelude.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"rand":["",[["distributions",[],["bernoulli.rs","distribution.rs","float.rs","integer.rs","mod.rs","other.rs","slice.rs","uniform.rs","utils.rs","weighted.rs","weighted_index.rs"]],["rngs",[["adapter",[],["mod.rs","read.rs","reseeding.rs"]]],["mock.rs","mod.rs","small.rs","std.rs","thread.rs","xoshiro256plusplus.rs"]],["seq",[],["index.rs","mod.rs"]]],["lib.rs","prelude.rs","rng.rs"]],\
"rand_chacha":["",[],["chacha.rs","guts.rs","lib.rs"]],\
"rand_core":["",[],["block.rs","error.rs","impls.rs","le.rs","lib.rs","os.rs"]],\
"syn":["",[["gen",[],["clone.rs"]]],["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","drops.rs","error.rs","export.rs","expr.rs","ext.rs","gen_helper.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]]\
}');
createSourceSidebar();
