[package]
name = "qitoy-prime-factorize"
version = "0.1.0"
edition = "2021"

[dependencies]
qitoy-prime-check = { path = "../check" }
qitoy-math-montgomery = { path = "../../math/montgomery" }
rand = { workspace = true }
