[package]
name = "verify_proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
syn = { workspace = true }
toml = "0.8.8"
