[package]
name = "verify_proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
prettyplease = "0.2.15"
regex = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
