name: test and doc

on: push

jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --workspace
        env:
          RUSTDOCFLAGS: --html-in-header katex.html

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
