name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - name: install oj-verify
        run: pip3 install -U online-judge-verify-helper

      - name: install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: install rust 1.70.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          override: true

      - name: install cargo udeps
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-udeps --locked

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: use oj-verify
        run: oj-verify run

      - name: cache stats
        run: oj-verify stats > .verify-helper/cache/stats.json

      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --workspace --features verify_docs
        env:
          RUSTDOCFLAGS: --html-in-header katex.html

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
